### ISSUE TITLE
Support Ruby

### ISSUE THREAD

**Issue by zakariamaaraki** [zakariamaaraki/RemoteCodeCompiler#26]

**Comment by Maufa42** [comment]
@zakariamaaraki **Assign** this to Me.
Would 🤝 love to Work with **you**

**Comment by zakariamaaraki** [comment]
@Maufa42 I've already done it, I forgot to update the status of the issue!

**Comment by zakariamaaraki** [comment]
closing the ticket, as this feature is already implemented

**Comment by Maufa42** [comment]
Great @zakariamaaraki Sir
