### ISSUE TITLE
setting memory and time limit

### ISSUE THREAD

**Issue by aldwnesx** [zakariamaaraki/RemoteCodeCompiler#3]
#!/usr/bin/env bash
ulimit -s 5
timeout --signal=SIGTERM 5 python3 test.py
exit $?

the above code doesn't seem to stop the python script. I tried with an infinite loop code in test.py

**Comment by zakariamaaraki** [comment]
this script is working for me with an infinite loop, can you provide your test.py file ?

**Comment by zakariamaaraki** [comment]
Hello, fixed ! 
Now we destroy the container if it gets stuck for some reason after a timeout.
