### ISSUE TITLE
Can you explain what is the purpose of use `createJavaEntrypointFile()`?

### ISSUE THREAD

**Issue by Miltonbhowmick** [zakariamaaraki/RemoteCodeCompiler#33]
I have read your blog https://dev.to/zakariamaaraki/how-to-develop-an-online-code-compiler-using-java-and-docker-1gpi 
Why can we not use only CMD to run main.py/main.java after submitting code from user?

Thanks in Advance.

**Comment by zakariamaaraki** [comment]
The idea is to run the submitted code inside a separate container to avoid affecting your main container or other containers with malicious code.

I hope this makes sense to you!

**Comment by Miltonbhowmick** [comment]
> The idea is to run the submitted code inside a separate container to avoid affecting your main container or other containers with malicious code.
> 
> I hope this makes sense to you!

Yeah it make sense! Thanks
