### ISSUE TITLE
Error while running on linux machine

### ISSUE THREAD

**Issue by sejalnaik** [zakariamaaraki/RemoteCodeCompiler#4]
/usr/bin/env: ‘bash\r’: No such file or directory

After building the image i tried running the container, but i am getting the above error,, after researching a bit i guess the problem may be because the Dockerfile or the entrypoint file may contain carriage returns somewhere in the code which the linux machine picks up in the path... can you try to resolve this by removing the carriage returns in the code or if you think there is some other problem then please do tell the solution, also i am running docker on a windows machine with a linux virtual machine on top of it, thank you

**Comment by zakariamaaraki** [comment]
Hello, thank you for reporting this issue, I'm running docker on a Linux machine and I do not have this problem. Please can you try to replace **ENTRYPOINT ["./entrypoint.sh"]** in the dockerfile by **CMD["java", "-jar", "compiler.jar"]** ?

**Comment by sejalnaik** [comment]
Hey thank you for the solution... its working now :)
