### ISSUE TITLE
There is no front end for testing. Is rest api supported?

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [zakariamaaraki/RemoteCodeCompiler#42]
![image](https://user-images.githubusercontent.com/37482171/207403025-ca7e3a66-0608-4244-a563-2d6623645d7f.png)

**Comment by rahulkumarsingh73690** [comment]
Where is docs - swagger-ui.html??

**Comment by zakariamaaraki** [comment]
Yes, or just go to http://localhost:8080/ you'll be redirected to the swagger-ui.html

**Comment by rahulkumarsingh73690** [comment]
Can you please send a postman demo?

**Comment by rahulkumarsingh73690** [comment]
{
    "timestamp": "2022-12-15T16:08:48.066+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/api/compile"
}

**Comment by zakariamaaraki** [comment]
Did you follow these steps [Redme.md]( https://github.com/zakariamaaraki/RemoteCodeCompiler/blob/master/README.md#getting-started) to run a container instance of the compiler ?

**Comment by rahulkumarsingh73690** [comment]
Yes, I followed all steps

**Comment by zakariamaaraki** [comment]
I updated the compiler to return messages of all unexpected exceptions. Can you please clone the current version, then run it and paste the returned message in the discussion so I can investigate the issue?

**Comment by rahulkumarsingh73690** [comment]
Thank you.

can I put command line expression in this compiler like input?

**Comment by zakariamaaraki** [comment]
Yes you can!

**Comment by rahulkumarsingh73690** [comment]
How? I am using https://github.com/judge0/judge0

**Comment by rahulkumarsingh73690** [comment]
is expectedOutput necessary to test the compiler?

**Comment by zakariamaaraki** [comment]
Yes expectedOutput is necessary, and input no.

**Comment by zakariamaaraki** [comment]
expectedOutput is used to return the verdict as a response

**Comment by rahulkumarsingh73690** [comment]
Why? How i suppose to know output if i am running code in compiler

**Comment by rahulkumarsingh73690** [comment]
I mean like this https://ide.judge0.com/

**Comment by zakariamaaraki** [comment]
This compiler was made for competitive programming, you can use it as an API. Imagine you want to create a platform for competitive programming where a user can submit his code, now how can you check that his code is valid? you can use this compiler just by sending the code written by the user and multiple test cases (inputs + expected outputs), and the memory limit and time limit that the code should not exceed :)

**Comment by rahulkumarsingh73690** [comment]
Ohh sorry but is it possible to use this as a normal compiler?

**Comment by zakariamaaraki** [comment]
No this is not the goal of this project :/
