### ISSUE TITLE
Error with building the necessary docker images

### ISSUE THREAD

**Issue by Shahman-01** [zakariamaaraki/RemoteCodeCompiler#43]
When starting docker according to the instructions and executing the command: ./environment/build.sh gives an error:
unable to prepare context: path "dockerfiles" not found
!!! Error while building compilation images !!!
Although judging by the file build.sh everything should work out as it should. I didn't change anything in the code. What could be the problem?

**Comment by Starlexxx** [comment]
Have you found a solution?

**Comment by Starlexxx** [comment]
I don't know, what was your problem, but I've solved this issue by runing build.sh via ```sh build.sh``` instead of ```./build.sh```

**Comment by Shahman-01** [comment]
Hello, yes, in the file buld.sh i added to the path environment
i replaced

docker image build -f
"dockerfiles/Dockerfile.${compilationDockerfilesPaths[$language]}.compilation"
-t "compiler.$language" "dockerfiles"
to

docker image build -f
"environment/dockerfiles/Dockerfile.${compilationDockerfilesPaths[$language]}.compilation"
-t "compiler.$language" "environment/dockerfiles"


вт, 18 апр. 2023 г. в 16:38, Andrew ***@***.***>:
