### ISSUE TITLE
Current version of the project does not work

### ISSUE THREAD

**Issue by NazarovSh** [zakariamaaraki/RemoteCodeCompiler#47]
**I followed the instructions step by step but this error occurred**,

"**error**": "Unable to find image 'compiler.java:latest' locally\ndocker: Error response from daemon: pull access denied for compiler.java, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.\nSee 'docker run --help'.\n",
<img width="1398" alt="Screenshot 2023-09-04 at 11 38 03" src="https://github.com/zakariamaaraki/RemoteCodeCompiler/assets/68165838/24bd5b8d-e869-4b69-b975-fa9bf5c5ea56">
<img width="1662" alt="Screenshot 2023-09-04 at 18 08 19" src="https://github.com/zakariamaaraki/RemoteCodeCompiler/assets/68165838/69d91e47-bb2d-4847-8189-7ea027930df1">
<img width="1666" alt="Screenshot 2023-09-04 at 18 09 25" src="https://github.com/zakariamaaraki/RemoteCodeCompiler/assets/68165838/0930dd9d-bed5-46ea-8504-473678c55f5b">

**also**
while using this (/api/compile/json) api endpoint why I should provide list of "convertedTestCases" in json ?

```
{
  "convertedTestCases": [ ⬅️ is it allowed to be here ❓
    {
      "expectedOutput": "string",
      "testCaseId": "string"
    }
  ],
  "language": "PYTHON",
  "memoryLimit": 0,
  "sourcecode": "string",
  "testCases": {
    "additionalProp1": {
      "expectedOutput": "string",
      "input": "string"
    },
    "additionalProp2": {
      "expectedOutput": "string",
      "input": "string"
    },
    "additionalProp3": {
      "expectedOutput": "string",
      "input": "string"
    }
  },
  "timeLimit": 0
}
```

**Comment by zakariamaaraki** [comment]
From the exception, i see that you don't have enough rights to pull the docker image. Make sure you have enough rights to use docker before launching the service.

For your second question, convertedTestCases is not part of the contract, it's something used internally by the service. Please follow the documentation in the readme.md file on how to make calls to the service.

**Comment by droidback** [comment]
THANKS! it worked, but still get some errors like this `java.security.policy: error parsing file:/app/security.policy: line 2: expected codeBase or SignedBy or Principal` while using multipart
<img width="1103" alt="Screenshot 2023-09-30 at 15 29 50" src="https://github.com/zakariamaaraki/RemoteCodeCompiler/assets/80504389/629a01c1-d9bb-4fda-a551-45e1fb3401c6">


source code
```import java.util.Scanner;

public class For20 {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = scanner.nextInt();

        for (int i = 1; i <= n; i++) {
            System.out.print(i+" ");
        }
    
    }
}
```

**inputs**
3
5

**expected outputs**
1 2 3
1 2 3 4 5

**Comment by zakariamaaraki** [comment]
Hi, I fixed that issue, a quote was missing in the security.policy file
