### ISSUE TITLE
Java compiler fails to load entrypoint

### ISSUE THREAD

**Issue by auadams** [zakariamaaraki/RemoteCodeCompiler#6]
It seems that the java compiler doesn't work because it can't load files. the fix i found was to modify the docker file.

From
ADD utility_java utility 

To
ADD utility_java utility_java

**Comment by auadams** [comment]
Also a mention you might want to consider using a more updated jdk than jdk11. using openjdk seems to work fine

**Comment by zakariamaaraki** [comment]
Hello, thank you for opening this issue, I updated the Dockerfile.
I'll look at the version of jdk.
