### ISSUE TITLE
Documentation or manual

### ISSUE THREAD

**Issue by pwnedDesal** [zakariamaaraki/RemoteCodeCompiler#8]
is there a manual here how to extend it? i want to add ruby

**Comment by zakariamaaraki** [comment]
Hello, i'll add a documentation by the end of the day on how to extend the compiler to support other languages. And then you can create a pull request.

**Comment by zakariamaaraki** [comment]
check out https://github.com/zakariamaaraki/RemoteCodeCompiler/blob/master/CONTRIBUTING.md
